# Generated by Django 4.2 on 2023-04-17 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('xendit_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('amount', models.FloatField(default=0.0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAID', 'PAID'), ('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=100)),
                ('expiry_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('paid_at', models.CharField(blank=True, default='PENDING', max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, default='PENDING', max_length=255, null=True)),
                ('created', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('updated', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
